#!/usr/bin/env bash
# specify a response for SIGTERM and SIGQUIT delete script
terminate() {
	rm /var/run/myscript.pid
	exit 0
}

# specify a response for SIGTERM
hate_kill() {
	echo "I hate the kill command"
	terminate
}

# specify a response for SIGINT
interrupt() {
	echo "Y U no love me?!"
}

# Trap SIGTERM
trap hate_kill SIGTERM

# Trap SIGQUIT
trap terminate SIGQUIT

# Trap SIGINT
trap interrupt SIGINT

# create a file contain PID
echo $$ >> /var/run/myscript.pid

# display "To infinity and beyond" infinitly with delay 2 seconds
while true
do
	echo "To infinity and beyond"
	sleep 2
done
