#!/usr/bin/env bash
# This script displays the content of the current directory in a list format


file="school"

if [ -e "$file" ]; then
    echo "school file exists"
    if [ -s "$file" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$file" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi