#!/bin/bash

# Change IP address of lo interface to 127.0.0.2
sudo ifconfig lo 127.0.0.2 netmask 255.0.0.0

# Connect to the DNS server (8.8.8.8) using telnet and send a request to change the IP address of facebook.com
echo -e "open 8.8.8.8 53\ndel facebook.com\nadd facebook.com A 8.8.8.8\n" | sudo telnet

# Alternatively, you can use nc to send the request:
# echo -e "del facebook.com\nadd facebook.com A 8.8.8.8\n" | sudo nc -w1 8.8.8.8 53 | cut -d " " -f 2- | tail -n +2

